name: 'na'
version: '1.0.0'
config-version: 2
profile: 'na'
model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
models:
  demo:
    metrics:
      +transient: false
      +materialized: table
vars:
  valid_percent_diff: 20