name: Publish docs

on: workflow_dispatch

jobs:
  publish_docs:
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ../target # The folder the action should deploy.
#
#      - name: Move files
#        run: |
#          rm -rf ./docs
#          mkdir ./docs
#          cp ./target/* ./docs
#
#      # https://github.com/marketplace/actions/github-action-for-committing-changes-to-a-repository
#      - name: Commit and push changes
#        uses: devops-infra/action-commit-push@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          commit_message: Published docs